In [1]:
import pandas as pd

train = pd.read_csv("p2_data/data_train.csv", header=None)
target = train.shape[1]-1
y = train[target].to_numpy()
X = train.drop(columns=[target]).to_numpy()

test = pd.read_csv("p2_data/data_test.csv", header=None)
y_test = test[target]
X_test = test.drop(columns=[target])


A)<br/>
Implement Random Forest:
1. It gets the number of trees (n) and their height
2. Samples the dataset with replacement(bootstrap) n times
3. For each tree randomly selects a few features
4. Train all trees
5. sum the predictions of all trees and use argmax

In [26]:
from sklearn import tree
import random
from sklearn.utils import resample
import numpy as np

class RandomForest:
    def __init__(self, n, depth):
        self.n = n
        self.depth = depth
        self.trees = []
        self.features = []
        self.samplesX = []
        self.samplesy = []
        self.n_classes = 2
        self.build()
        
    def build(self):
        for i in range(self.n):
            clf = tree.DecisionTreeClassifier(max_depth=self.depth)
            self.trees.append(clf)
            
    def fit(self, X, y, n):
        self.n_classes = len(np.unique(y))
        for i in range(self.n):
            self.bootstrap(X, y)
            self.random_features(n, X.shape[1]-1)
            self.trees[i] = self.trees[i].fit(self.samplesX[i][:, self.features[i]], self.samplesy[i])
            
    def predict(self, X):
        predictions = np.zeros(shape=(len(X), self.n_classes))
        for i in range(self.n):
            predictions = np.add(predictions,self.trees[i].predict_proba(X[:, self.features[i]]))
            
        return np.argmax(predictions, axis=1)

    def bootstrap(self, X, y):
        r = random.randint(0, 1000)
        bootX = resample(X, replace=True, n_samples=len(X), random_state=r)
        booty = resample(y, replace=True, n_samples=len(X), random_state=r)
        self.samplesX.append(bootX)
        self.samplesy.append(booty)
        
    def random_features(self, n, n_features):
        features = []
        for i in range(n):
            features.append(random.randint(0, n_features))
        self.features.append(features)


In [27]:
clf = RandomForest(15, 3)
clf.fit(X, y, 3)

In [28]:
print(y)
predictions = clf.predict(X)
print(predictions)

[8 2 1 ... 5 1 7]
[8 2 1 ... 3 2 7]


In [29]:
from sklearn.metrics import accuracy_score
accuracy_score(y, predictions)

0.8155858019749133

In [20]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, predictions)

array([[742,   6,   0,   0,   4,   0,  11,   0,  17,   0],
       [  0, 542, 160,  55,  12,   0,   4,   0,   0,   6],
       [  0,   8, 753,   1,   1,   0,   3,  13,   1,   0],
       [  0,  15,   1, 697,   1,   0,   0,   0,   0,   5],
       [  1,   2,   0,   1, 751,   1,  20,   0,   0,   4],
       [  1,   0,   0, 179,   1, 456,   4,   0,   2,  77],
       [  0,   0,   2,   3,   2,   1, 703,   9,   0,   0],
       [  0,  90,   4,   5,   1,   1,   7, 658,  11,   1],
       [129,  12,   6,  11,   5,   4,  10, 108, 379,  55],
       [  1,  74,   0,  87,  20,   2,   0,   0,   2, 533]])

B)<br/>
Implement AdaBoost

In [75]:
from sklearn import tree
import random
from sklearn.utils import resample
import numpy as np

class AdaBoost:
    def __init__(self, n):
        self.n = n
        self.trees = [] 
        self.alphas = []
        self.build()
        
    def build(self):
        for i in range(self.n):
            stump = tree.DecisionTreeClassifier(max_depth=1)
            self.trees.append(stump)
            
    def fit(self, X, y):
        n_samples, _ = X.shape
        
        # init weight
        w = np.full(n_samples, (1/n_samples))
        
        for i in range(self.n):
            self.trees[i] = self.trees[i].fit(X, y, sample_weight=w)
            predictions = self.trees[i].predict(X)

#             print(predictions)
            
            missclassified = w[y != predictions]
            error = sum(missclassified)
            
            print(np.sum(w))
            print(missclassified.shape)
            print(np.sum(missclassified))
            print("++++++++++++")
            
            EPS = 1e-10
            alpha = 0.5 * np.log((1-error) / (error+EPS))
            self.alphas.append(alpha)
           
            w *= np.exp(-alpha * y * predictions)
            w /= np.sum(w)
            
            
    def predict(self, X):
        predictions = np.array([])
        for i in range(self.n):
            np.append(predictions, self.alphas[i] * self.trees[i].predict_proba(X))
        print(predictions)
        
        y_pred = np.sum(predictions, axis=0)
        return np.sign(predictions)

In [76]:
clf = AdaBoost(10)
clf.fit(X, y)

# print(y)
predictions = clf.predict(X)
# print(predictions)

# accuracy_score(y, predictions)

0.9999999999999998
(5944,)
0.7931678676274352
++++++++++++
0.9999999999999998
(6106,)
0.09773139668897887
++++++++++++
0.9999999999999998
(5988,)
1.1837401444314504e-05
++++++++++++
1.0
(6694,)
8.572617596505707e-06
++++++++++++
1.0
(5988,)
8.029670221883996e-06
++++++++++++
1.0
(6714,)
8.03124432881917e-06
++++++++++++
1.0
(6714,)
8.03124432881917e-06
++++++++++++
1.0
(6714,)
8.03124432881917e-06
++++++++++++
1.0
(6714,)
8.03124432881917e-06
++++++++++++
1.0
(6714,)
8.03124432881917e-06
++++++++++++
[]
